# file: docker-compose.yml
version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev-key-change-in-production
      - TON_MAINNET=true
      - TONCENTER_API_KEY=
    volumes:
      - .:/app
    restart: unless-stopped
