# file: render.yaml
services:
  - type: web
    name: ton-staking-portal
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: TON_MAINNET
        value: "true"
      - key: TONCENTER_API_KEY
        sync: false
      - key: DATABASE_URL
        value: "postgresql://ittoken_db_user:Xm98VVSZv7cMJkopkdWRkgvZzC7Aly42@dpg-d0visga4d50c73ekmu4g-a.frankfurt-postgres.render.com/ittoken_db"
      - key: DB_SCHEMA
        value: "ton_staking_portal"
